table Dim_Product
	lineageTag: 708d8b79-d9f0-419a-b394-e3f53ccfd737

	column Product_ID
		dataType: int64
		formatString: 0
		lineageTag: 2e95eda0-e13e-4b9c-855b-3ebb0f9afa8f
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: f6453ddc-5fd0-4477-9267-a105105911cf
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Product_Desc
		dataType: string
		lineageTag: 1a3435f0-a8ce-448e-82b3-debe76693fbe
		summarizeBy: none
		sourceColumn: Product_Desc

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: 0
		lineageTag: b0878b06-a323-4f76-bfaa-076089955b41
		summarizeBy: none
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source = ```
				let
				    Dim_Product = let
				    Source = Excel.Workbook(File.Contents("C:/Users/10741438/OneDrive - LTIMindtree/Desktop/LookerMetadata_Json/Sample_Sales_Data.xlsx"), null, true),
				    
				    // Base Table extraction logic
				    Fact_Sales = Source{[Item="Fact_Sales",Kind="Sheet"]}[Data],
				    Dim_Date = Source{[Item="Dim_Date",Kind="Sheet"]}[Data],
				    Dim_Product = Source{[Item="Dim_Product",Kind="Sheet"]}[Data],
				    Dim_Location = Source{[Item="Dim_Location",Kind="Sheet"]}[Data],
				    Dim_Customer = Source{[Item="Dim_Customer",Kind="Sheet"]}[Data]
				in
				    Dim_Product,
				    #"Promoted Headers" = Table.PromoteHeaders(Dim_Product, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_ID", Int64.Type}, {"Product_Name", type text}, {"Product_Desc", type text}, {"Price", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

